### ISSUE TITLE
how to change input to chinese

### ISSUE THREAD

**Issue by LebronJames0423** [abetlen/ai-voice-chat#1]
can you tell me how to change input to chinese ?   thanks a lot

**Comment by abetlen** [comment]
Hi there!

Currently, there's no settings in the UI to change the language but if you're running it locally you can set the language of the speech synthesis and recognition systems [here](https://github.com/abetlen/ai-voice-chat/blob/69c5ab7c7346805bf804df398bcd6b99e7ae80b1/src/App.tsx#L139) and [here](https://github.com/abetlen/ai-voice-chat/blob/69c5ab7c7346805bf804df398bcd6b99e7ae80b1/src/App.tsx#L373). You should be able to set these to `zh-CN` assuming your browser supports this (you can check by opening up a console and running `window.speechSynthesis.getVoices()`).

I'm not sure how well gpt-3.5-turbo does on Chinese however, so that may be a different story.
